version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: jwt-service
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: jwt-postgres
    environment:
      POSTGRES_DB: jwt-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
