basePath: /
definitions:
  handler.RefreshRequest:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  handler.TokenPair:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Выдаёт и обновляет Access/Refresh JWT.
  title: JWT Auth Service API
  version: "1.0"
paths:
  /auth:
    get:
      description: Принимает GUID (или генерирует новый) и возвращает Access‑/Refresh‑пару.
      parameters:
      - description: Клиентский GUID
        in: query
        name: guid
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.TokenPair'
        "400":
          description: invalid guid format
          schema:
            type: string
        "500":
          description: internal error
          schema:
            type: string
      summary: Login / первичная авторизация
      tags:
      - auth
  /refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: Старая пара токенов
        in: body
        name: tokens
        required: true
        schema:
          $ref: '#/definitions/handler.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.TokenPair'
        "400":
          description: invalid request body
          schema:
            type: string
        "401":
          description: unauthorized
          schema:
            type: string
      summary: Refresh tokens
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    description: '"Bearer <token>"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
